siteTitle = "Roma Psicologia"
url = "http://www.romapsicologia.it"
linkPrefix = "/notUsedYet"
email = "info@romapsicologia.it"
twitter = "@Psicoroma"
facebook = "consulenzapsicologica.roma.5"

[js]
head = """
if ('classList' in document.createElement('div') && 'querySelector' in document && 'addEventListener' in window && Array.prototype.forEach) {
  document.documentElement.classList += 'js';
  var script = document.createElement('script');
  script.src = '/bundle.js';
  document.getElementsByTagName('body')[0].appendChild(script);
}
"""
analytics = """
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-35604519-1', 'auto');
ga('send', 'pageview');
"""
font = """
var font = new FontFaceObserver('leagueSpartan-bold');
font.load().then(function () {
  document.documentElement.className += ' webfonts-loaded';
});
"""

favicons = '''
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png?v=1">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png?v=1">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png?v=1">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png?v=1">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png?v=1">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png?v=1">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png?v=1">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png?v=1">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png?v=1">
<link rel="icon" type="image/png" href="/favicon-32x32.png?v=1" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png?v=1" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png?v=1" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png?v=1" sizes="16x16">
<link rel="manifest" href="/manifest.json?v=1">
<link rel="mask-icon" href="/safari-pinned-tab.svg?v=1" color="#1f262e">
<link rel="shortcut icon" href="/favicon.ico?v=1">
<meta name="apple-mobile-web-app-title" content="example.com">
<meta name="application-name" content="example.com">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-TileImage" content="/mstile-144x144.png?v=1">
<meta name="theme-color" content="#1f262e">
'''

[header]
text = '''
<span class="right@md">

</span>
'''

[mission]
title = "mission"
blurb = '''
Un servizio di consulenza su problemi 
'''
dir = "mission"

[work]
title = "attività di prossimo avvio"
blurb = "Segui le nostre proposte per la manutenzione professionale"
dir = "work"

[writing]
title = "Blog"
blurb = "Approfondimenti teorici, contesti di intervento e questioni che ci interessano"
dir = "writing"

[contatti]
title = "Contatti"
info = "Per informazioni o fissare un appuntamento."
blurb = "I nostri contatti"
telefono = "(39) 393 556 0220"
indirizzo = "Ci troviamo in via Tuscolana (altezza metro Lucio Sestio)"
key = "AIzaSyB7uh9F1MAA3zFAiiDLGreD6CSRg6wGPEU"
lat = 41.859868
lng = 12.557095

[about]
title = "Chi Siamo"
text = '''
<div class="left@md mb-3 flexItem-100 w-100 items-center">
    <span class="right@md" mr-0>
        <iframe class="avatar mr-0" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fconsulenzapsicologica.roma.5&tabs&width=100&height=200&small_header=false&adapt_container_width=true&hide_cover=true&show_facepile=false&appId=351368248230367" width="180" height="250" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
    </span>
    <p class="fs-4">          
    </p>
</div>
<div class="left@sm w-50@sm pr-2">
  <a href="https://it.linkedin.com/in/carmela-mastroianni-23502226"><h3 class="h4 my-1">Dott.ssa Mastroianni</h3></a>
  <div class="fs-5">
      <img src="carmela-mastroianni.jpg" class="left mr-1 flexItem-25 w-33 circle" alt="Carmela Mastroianni"/>
      <div class="mt-1@sm flexItem-75 w-auto pl-0 pr-1">
        Psicologo e Psicoterapeuta specialista in Psicoterapia Psicoanalitica.
        <p>Iscrizione Ordine degli Psicologi del Lazio n°18894</p>
      </div>
  </div>
</div>
<div class="left@sm w-50@sm pl-2">
  <a href="https://it.linkedin.com/in/paolo-olivieri-64a4884a"><h3 class="h4 my-1">Dott. Olivieri</h3></a>
  <div class="fs-5">
      <img src="paolo-olivieri.jpg" class="left mr-1 flexItem-25 w-33 circle" alt="Paolo Olivieri"/>
      <div class="mt-1@sm flexItem-75 w-auto pl-0  pr-1">
        Psicologo e Psicoterapeuta specialista in Psicoterapia Psicoanalitica. <p>Iscrizione Ordine degli Psicologi del Lazio n° 19102</p>
      </div>
  </div>
</div>
'''
