siteTitle = "Roma Psicologia"
url = "http://www.romapsicologia.it"
linkPrefix = "/notUsedYet"
email = "info@romapsicologia.it"
twitter = "@Psicoroma"
facebook = "consulenzapsicologica.roma.5"

[js]
head = """
if ('classList' in document.createElement('div') && 'querySelector' in document && 'addEventListener' in window && Array.prototype.forEach) {
  document.documentElement.classList += 'js';
  var script = document.createElement('script');
  script.src = '/bundle.js';
  document.getElementsByTagName('body')[0].appendChild(script);
}
"""
analytics = """
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-xxxxxxxx-x', 'auto');
ga('send', 'pageview');
"""
font = """
var font = new FontFaceObserver('leagueSpartan-bold');
font.load().then(function () {
  document.documentElement.className += ' webfonts-loaded';
});
"""

favicons = '''
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png?v=1">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png?v=1">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png?v=1">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png?v=1">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png?v=1">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png?v=1">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png?v=1">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png?v=1">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png?v=1">
<link rel="icon" type="image/png" href="/favicon-32x32.png?v=1" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png?v=1" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png?v=1" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png?v=1" sizes="16x16">
<link rel="manifest" href="/manifest.json?v=1">
<link rel="mask-icon" href="/safari-pinned-tab.svg?v=1" color="#1f262e">
<link rel="shortcut icon" href="/favicon.ico?v=1">
<meta name="apple-mobile-web-app-title" content="example.com">
<meta name="application-name" content="example.com">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="msapplication-TileImage" content="/mstile-144x144.png?v=1">
<meta name="theme-color" content="#1f262e">
'''

[header]
text = '''
<p><span class="bold">la psicologia in rete e sul territorio</span></p>
'''

[mission]
title = "mission"
blurb = '''
Vogliamo creare spazio di frequentazione con la psicologia per fare proposte e raccogliere idee e riscontri.
'''
dir = "mission"

[work]
title = "Attività di prossimo avvio"
blurb = "I sintomi portati in consulenza sono indicatori che ci aiutano a capire il problema vissuto nei contesti di appartenenza. "
dir = "work"

[writing]
title = "Blog"
blurb = "Nel nostro lavoro aiutiamo le persone a sviluppare una competenza a progettare, in altri termini a tenere insieme desideri e limiti di realtà."
dir = "writing"

[about]
title = "Chi Siamo"
text = '''
<div class="left@md mb-3 items-center">
  <img src="/avatar.jpg" srcset="/avatar@2x.jpg 2x" width="150" height="150" alt="" class="avatar flexItem-33 w-33 mx-auto my-auto circle border borderColor-light" />
  <p class="fs-4">Proponiamo uno specifico momento di intervento psicologico che si occupa degli agiti emozionali collusivi nei sistemi di appartenenza, attraverso l'utilizzo di relazioni psicoanaliticamente fondate.</p>
</div>
<div class="left@sm w-50@sm">
  <a href="https://it.linkedin.com/in/carmela-mastroianni-23502226"><h3 class="h4 my-1">Dott.ssa Mastroianni</h3></a>
  <div class="fs-6">
      <img src="carmela-mastroianni.jpg" class="left@sm flexItem-33 w-33 mx-1 my-auto circle border borderColor-light" width="150" height="150" alt="Carmela Mastroianni">
      <div class="mt-1@sm">
        <div class="mt-1@sm">Psicologa Clinica e Psicoterapeuta specialista in Psicoterapia Psicoanalitica </div>
        <div class="mt-1@sm">Iscrizione Ordine degli Psicologi del Lazio n° 18894 </div>
      </div>
  </div>
</div>
<div class="left@sm w-50@sm">
  <a href="https://it.linkedin.com/in/paolo-olivieri-64a4884a"><h3 class="h4 my-1">Dott. Olivieri</h3></a>
  <div class="fs-6">
      <img src="paolo-olivieri.jpg" class="left@sm flexItem-33 w-33 mx-1 my-auto circle border borderColor-light" width="150" height="150" alt="Paolo Olivieri">
      <div class="mt-1@sm">
        <div class="mt-1@sm">Psicologo Clinico e Psicoterapeuta specialista in Psicoterapia Psicoanalitica</div>
        <div class="mt-1@sm">Iscrizione Ordine degli Psicologi del Lazio n° 19102</div>
      </div>
  </div>
</div>
'''
